CREATE TABLE user (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL,
	password VARCHAR(100) NOT NULL,
	linkedin VARCHAR(128) NOT NULL,
	CONSTRAINT user_PK PRIMARY KEY (id)
);
